production:
  MATEMATICUS_DATABASE_USERNAME: "<%= ENV['DATABASE_USERNAME'] %>"
  MATEMATICUS_DATABASE_PASSWORD: "<%= ENV['DATABASE_PASSWORD'] %>"
  MATEMATICUS_DATABASE_NAME: "<%= ENV['DATABASE_NAME'] %>"
